version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    assignees:
      - "Nick-Mazuk"
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: daily
    assignees:
      - "Nick-Mazuk"