[workspace]

members = [
    "cli",
    "utils/target",
    "utils/build-graph",
    "utils/test",
    "utils/files",
]

[workspace.dependencies]
clap = { version = "4.3.10", features = ["derive"] }
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.5"
toml_edit = "0.19.11"
vfs = "0.9.0"
virtual-io = "0.1.0"
