[workspace]

members = [
    "cli",
    "protos",
    "thor",
    "utils/build-graph",
    "utils/files",
    "utils/macros",
    "utils/target",
    "utils/test",
    "version-api",
]

[workspace.dependencies]
base64 = "0.21.2"
bytes = "1.4.0"
clap = { version = "4.3.10", features = ["derive"] }
prost = "0.11.9"
prost-build = "0.11.9"
protobuf-src = "1.1.0"
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.5"
toml_edit = "0.19.11"
url = "2.4.0"
vfs = "0.9.0"
virtual-io = "0.1.0"
worker = "0.0.17"

[profile.release]
strip = true
opt-level = 2
lto = true
codegen-units = 1
