[package]
name = "build-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
files.workspace = true
target.workspace = true
toml.workspace = true
vfs.workspace = true
virtual-io.workspace = true

[dev-dependencies]
test-utils.workspace = true
