[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs.workspace = true
files.workspace = true
tokio.workspace = true
vfs.workspace = true
virtual-io.workspace = true
version.workspace = true
