[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
files = { path = "../utils/files" }
toml.workspace = true
vfs.workspace = true
virtual-io.workspace = true

[profile.release]
strip = true
opt-level = 3
lto = true
