[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
files = { path = "../utils/files" }
protobuf.workspace = true
protos = { path = "../protos" }
vfs.workspace = true
virtual-io.workspace = true
