[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[dependencies]
base64.workspace = true
bytes.workspace = true
prost.workspace = true
url.workspace = true
version = { path = "../utils/version" }

[build-dependencies]
protobuf-src.workspace = true
prost-build.workspace = true
