on: [pull_request]
name: benchmark pull requests
jobs:
    runBenchmark:
        name: run benchmark
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - uses: boa-dev/criterion-compare-action@v3
              with:
                  branchName: ${{ github.base_ref }}
                  # Optional. Default is `${{ github.token }}`.
                  token: ${{ secrets.GITHUB_TOKEN }}
