name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install cargo
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - uses: Swatinem/rust-cache@v2

    - run: (cd ./version-api && npx wrangler deploy)
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
