name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: rustup toolchain install stable --profile minimal
    - run: rustup component add cargo
    - uses: Swatinem/rust-cache@v2

    - name: Publish version api
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        workingDirectory: './version-api'