name: Bump version
on:
  schedule:
    # Every day at midnight pacific time
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: fregante/setup-git-user@v2.0.1

      # Create and push a new tag with the current date
      - run: git tag -a ${{ steps.date.outputs.date }} -m "Nightly"
      - run: git push "https://cambiata-team:${{ secrets.ACCESS_TOKEN }}@github.com/cambiata-team/buri.git" ${{ steps.date.outputs.date }}