name: Release

on:
  schedule:
    # Every day at midnight pacific time
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: fregante/setup-git-user@v2.0.1

      - name: Create a tag
        run: git tag -a ${{ steps.date.outputs.date }} -m "Nightly"

      - name: Push tag
        run: git push origin ${{ steps.date.outputs.date }}

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: refs/tags/${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          draft: true
          prerelease: false

  build-and-upload:
    name: Build and upload
    needs: create-release
    runs-on: ${{ matrix.target.os }}

    strategy:
      matrix:
        target:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
        binary: [cli, thor]

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.binary }}
          target: ${{ matrix.target.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          checksum: sha256

  publish-release:
    name: Publish Release
    needs: [build-and-upload, create-release]
    runs-on: ubuntu-latest

    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.create-release.outputs.release_id }}

      - name: Sync with our version API
        id: webhook
        uses: satak/webrequest-action@master
        with:
          url: https://version-api.buri-lang.dev/add-release
          method: POST
          payload: '{ "release_id": "${{ needs.create-release.outputs.release_id }}"}'
          headers: '{"Authentication": "${{ secrets.RELEASE_WEBHOOK_SECRET }}"}'

      - run: echo ${{ steps.webhook.outputs.output }}
